name: ESLint

on:
  push:
    branches: ['main']
  pull_request:

jobs:
  eslint:
    name: Code scanning with ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Set up Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run the ESLint scanner
        run: npm run lint
