name: ESLint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  eslint:
    name: Code scanning with ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run the ESLint scanner
        run: npm run lint
