name: Prettier

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install

      - name: Run ESLint scanner
        run: npm run format:check
