name: Prettier

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  prettier:
    name: Code scanning with Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run the Prettier scanner
        run: npm run format:check
